name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone the target Hugging Face Space
        run: |
          git clone https://faihaj:${{ secrets.HF_FAKEDET }}@huggingface.co/spaces/faihaj/fakeDet hf_space_repo

      - name: Copy app files
        run: |
          cp -r hf_space/* hf_space_repo/
          cd hf_space_repo
          git add .
          git commit -m "Sync updated app from GitHub"
          git push
